name: Auto Deploy
on: 
  push: 
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set up Go
      uses: actions/setup-go@master
      with:
        go-version: 1.19
    
    - name: Build
      uses: go build -v ./...

    
    #- name: Run a shell
    #  shell: bash
    #  run: 
    #    sh go.sh
    #提交时转换为LF，检出时不转换
    #git config --global core.autocrlf input

            
